// Exercise pools for category 4 (adverbs) and category 5 (do / don't / doesn't).
import { P, conjugations, flip, fw, match, mc, wo, type PoolItem } from "./builders";

export const adverbManner: PoolItem[] = [
  mc("Choose the correct adverb", "She sings ___.", ["beautifully", "beautiful", "beauty", "more beautiful"], "beautifully",
    "Untuk menjelaskan cara, pakai adverb: beautiful + -ly menjadi beautifully."),
  mc("Choose the correct adverb", "He drives very ___.", ["careful", "carefully", "carefuly", "care"], "carefully",
    "Careful + -ly menjadi carefully, dengan dua huruf l."),
  mc("Choose the correct adverb", "They speak English ___.", ["fluently", "fluent", "fluence", "more fluent"], "fluently",
    "Fluent + -ly menjadi fluently."),
  mc("Choose the correct adverb", "She closed the door ___.", ["quietly", "quiet", "quietness", "quieter"], "quietly",
    "Quiet + -ly menjadi quietly, menjelaskan cara menutup pintu."),
  mc(P.chooseWord, "My sister writes ___.", ["well", "good", "goodly", "better good"], "well",
    "Good adalah kata sifat, adverbnya well."),
  mc(P.which, "Pick the correct sentence.",
    ["They work hard every day.", "They work hardly every day.", "They work hardly."], "They work hard every day.",
    "Adverb dari hard adalah hard. Kata hardly berarti hampir tidak pernah."),
  mc(P.which, "Pick the correct sentence.",
    ["He answered the question quickly.", "He answered quickly the question.", "He quickly answered question the."],
    "He answered the question quickly.", "Adverb of manner diletakkan setelah objek."),
  ...conjugations("Complete the sentence with the adverb", [
    ["Please speak ___ (slow).", "slowly", "Slow + -ly menjadi slowly."],
    ["She finished the test ___ (easy).", "easily", "Easy berakhiran konsonan + y, jadi y berubah menjadi i: easily."],
    ["He runs ___ (quick).", "quickly", "Quick + -ly menjadi quickly."],
    ["They waited ___ (patient).", "patiently", "Patient + -ly menjadi patiently."],
    ["She sang ___ (happy).", "happily", "Konsonan + y menjadi -ily: happily."],
  ]),
  wo(P.order, "He answered the question quickly", "Adverb of manner diletakkan setelah objek."),
  wo(P.order, "She speaks English fluently", "Adverb diletakkan setelah objek."),
  wo(P.order, "They walked home slowly", "Adverb of manner di akhir kalimat."),
  match("Match each adjective to its adverb", [
    ["quick", "quickly"], ["slow", "slowly"], ["easy", "easily"], ["good", "well"],
  ], "Kebanyakan cukup ditambah -ly. Konsonan + y menjadi -ily. Good tidak beraturan: well."),
  match("Match each adjective to its adverb", [
    ["careful", "carefully"], ["happy", "happily"], ["hard", "hard"], ["quiet", "quietly"],
  ], "Hard tidak berubah. Happy menjadi happily."),
  fw(P.write, "Write one sentence about how you do something, using an adverb of manner.", ["adverb of manner"],
    "I speak English slowly.", "Gunakan adverb yang menjelaskan cara."),
  fw(P.write, "Write one sentence about how someone in your family works.", ["adverb of manner"],
    "My father drives carefully.", "Gunakan adverb berakhiran -ly setelah kata kerja."),
];

export const adverbTime: PoolItem[] = [
  mc("Choose the correct adverb of time", "I saw that movie ___.", ["yesterday", "tomorrow", "soon", "later"], "yesterday",
    "Kata kerja saw adalah bentuk lampau, jadi keterangannya yesterday."),
  mc("Choose the correct adverb of time", "She will call you ___.", ["later", "yesterday", "last night", "ago"], "later",
    "Will menandakan masa depan, jadi keterangannya later."),
  mc("Choose the correct adverb of time", "They are eating ___.", ["now", "yesterday", "last year", "ago"], "now",
    "Present continuous menandakan kegiatan sekarang."),
  mc("Choose the correct adverb of time", "We went to Bali ___.", ["last year", "next year", "tomorrow", "soon"], "last year",
    "Went adalah bentuk lampau, jadi keterangannya last year."),
  mc("Choose the correct adverb of time", "He will arrive ___.", ["soon", "yesterday", "last week", "ago"], "soon",
    "Will menandakan masa depan, jadi soon."),
  mc(P.which, "Pick the correct sentence.",
    ["I finished my homework already.", "I already finished homework my.", "Already I my homework finished."],
    "I finished my homework already.", "Susunannya subjek + kata kerja + objek, lalu keterangan waktu."),
  mc(P.which, "Pick the correct sentence.",
    ["She visited her aunt last week.", "She visited last week her aunt.", "Last week she her aunt visited."],
    "She visited her aunt last week.", "Keterangan waktu biasanya diletakkan di akhir."),
  ...conjugations("Complete the sentence with the correct verb form", [
    ["He ___ (go) to Bandung last month.", "went", "'Last month' menandakan waktu lampau, jadi went."],
    ["They ___ (arrive) tomorrow.", "will arrive", "'Tomorrow' menandakan masa depan, jadi will + kata kerja dasar."],
    ["She ___ (watch) a film yesterday.", "watched", "'Yesterday' menandakan waktu lampau: watched."],
    ["We ___ (meet) him last Friday.", "met", "Bentuk lampau dari meet adalah met."],
  ]),
  wo(P.order, "We visited the museum yesterday", "Keterangan waktu diletakkan di akhir kalimat."),
  wo(P.order, "They will arrive soon", "Subjek + will + kata kerja dasar + keterangan waktu."),
  wo(P.order, "She finished her work early", "Keterangan waktu di akhir."),
  wo(P.order, "I will call you later", "Keterangan waktu later di akhir kalimat."),
  match("Match each adverb to its time", [
    ["yesterday", "past"], ["now", "present"], ["tomorrow", "future"], ["last week", "past"], ["soon", "future"],
  ], "Yesterday dan last week menunjuk masa lalu, now sekarang, tomorrow dan soon masa depan."),
  match("Match each adverb to its time", [
    ["last year", "past"], ["today", "present"], ["next month", "future"], ["an hour ago", "past"],
  ], "Ago dan last menunjuk masa lalu, next menunjuk masa depan."),
  fw(P.write, "Write one sentence about something you did, using an adverb of time.", ["past simple", "adverb of time"],
    "I studied English yesterday.", "Gunakan bentuk lampau dengan keterangan waktu di akhir."),
  fw(P.write, "Write one sentence about your plan, using an adverb of time.", ["future with will", "adverb of time"],
    "I will visit my friend tomorrow.", "Gunakan will + kata kerja dasar dengan keterangan waktu."),
];

export const adverbPlace: PoolItem[] = [
  mc("Choose the correct adverb of place", "Please sit ___.", ["here", "now", "quickly", "always"], "here",
    "Here menjelaskan tempat. Now waktu, quickly cara, always frekuensi."),
  mc("Choose the correct adverb of place", "The children are playing ___.", ["outside", "yesterday", "slowly", "never"], "outside",
    "Outside menjelaskan tempat bermain."),
  mc("Choose the correct adverb of place", "Come ___ and see my new bike.", ["here", "there", "away", "then"], "here",
    "Here berarti di tempat pembicara, there berarti tempat yang jauh."),
  mc("Choose the correct adverb of place", "My books are ___.", ["upstairs", "tomorrow", "quietly", "often"], "upstairs",
    "Upstairs menjelaskan tempat, yaitu di lantai atas."),
  mc("Choose the correct adverb of place", "It is cold, so we will stay ___.", ["inside", "slowly", "later", "always"], "inside",
    "Inside berarti di dalam, lawan katanya outside."),
  mc(P.which, "Pick the correct sentence.",
    ["She looked everywhere for her keys.", "She looked for everywhere her keys.", "Everywhere she looked her keys for."],
    "She looked everywhere for her keys.", "Adverb of place diletakkan setelah kata kerja."),
  mc(P.which, "Pick the correct sentence.",
    ["He put his bag there.", "He put there his bag.", "There he his bag put."], "He put his bag there.",
    "Adverb of place diletakkan setelah objek."),
  ...conjugations("Complete the sentence with an adverb of place", [
    ["It is raining, so we will stay ___ (in the house).", "inside", "Inside berarti di dalam rumah."],
    ["My room is ___ (on the upper floor).", "upstairs", "Upstairs berarti di lantai atas."],
    ["The cat is sleeping ___ (not in the house).", "outside", "Outside berarti di luar."],
  ]),
  wo(P.order, "My cat is sleeping upstairs", "Adverb of place diletakkan setelah kata kerja."),
  wo(P.order, "I put my books there", "Adverb of place diletakkan setelah objek."),
  wo(P.order, "The children are playing outside", "Adverb of place setelah kata kerja."),
  wo(P.order, "She looked everywhere for it", "Adverb of place setelah kata kerja."),
  match("Match each adverb to its type", [
    ["here", "place"], ["tomorrow", "time"], ["upstairs", "place"], ["carefully", "manner"],
  ], "Here dan upstairs menjelaskan tempat, tomorrow waktu, carefully cara."),
  match("Match each adverb to its type", [
    ["outside", "place"], ["yesterday", "time"], ["slowly", "manner"], ["everywhere", "place"],
  ], "Outside dan everywhere menjelaskan tempat."),
  fw(P.write, "Write one sentence about where you study, using an adverb of place.", ["adverb of place"],
    "I study upstairs every evening.", "Gunakan adverb yang menjelaskan tempat."),
  fw(P.write, "Write one sentence about where your family eats dinner.", ["adverb of place"],
    "We eat dinner inside.", "Gunakan adverb tempat setelah kata kerja."),
];

export const adverbFrequency: PoolItem[] = [
  mc(P.choose, "They ___ tired on Monday.", ["are usually", "usually are", "are usually being"], "are usually",
    "Setelah am, is, atau are, adverb diletakkan setelah kata kerja."),
  mc("Choose the best adverb", "I ___ eat vegetables. I really don't like them.", ["always", "never", "usually", "often"], "never",
    "'Really don't like' berarti 0% dari waktu, jadi never."),
  mc("Choose the best adverb", "She ___ drinks coffee. She loves it.", ["never", "always", "rarely", "seldom"], "always",
    "'She loves it' menandakan 100% dari waktu, jadi always."),
  mc(P.choose, "He ___ late for class.", ["is often", "often is", "is being often"], "is often",
    "Dengan 'to be', adverb diletakkan setelah kata kerja."),
  mc(P.which, "Pick the sentence with the adverb in the right place.",
    ["She usually goes to bed at 10.", "She goes usually to bed at 10.", "She goes to bed usually at 10."],
    "She usually goes to bed at 10.", "Adverb diletakkan sebelum kata kerja utama."),
  mc(P.which, "Pick the correct sentence.",
    ["We often play football.", "We play often football.", "Often we play football often."],
    "We often play football.", "Adverb of frequency diletakkan sebelum kata kerja utama."),
  ...conjugations("Complete the sentence using the words in brackets", [
    ["We ___ (often / play) football on Saturday.", "often play", "Adverb diletakkan sebelum kata kerja utama."],
    ["She ___ (always / read) before bed.", "always reads", "Adverb sebelum kata kerja, dan 'she' memakai bentuk -s."],
    ["They ___ (never / eat) meat.", "never eat", "Adverb sebelum kata kerja utama."],
    ["He ___ (sometimes / walk) to school.", "sometimes walks", "Adverb sebelum kata kerja, dan 'he' memakai -s."],
  ]),
  wo(P.order, "I always eat breakfast", "Adverb of frequency diletakkan sebelum kata kerja utama."),
  wo(P.order, "She never drinks coffee", "Adverb sebelum kata kerja utama, dan 'she' memakai bentuk -s."),
  wo(P.order, "He is always late", "Dengan 'to be', adverb diletakkan setelahnya."),
  wo(P.order, "They often visit their grandmother", "Adverb sebelum kata kerja utama."),
  wo(P.order, "We are usually busy", "Setelah are, adverb diletakkan sesudahnya."),
  match("Match each adverb to how often it means", [
    ["always", "100%"], ["usually", "about 85%"], ["often", "about 60%"], ["sometimes", "about 30%"], ["never", "0%"],
  ], "always = 100%, usually = sekitar 85%, often = sekitar 60%, sometimes = sekitar 30%, never = 0%."),
  match("Match each sentence to its adverb position", [
    ["I ___ eat breakfast", "before the main verb"], ["He is ___ late", "after is"],
    ["They ___ play football", "before the main verb"], ["We are ___ busy", "after are"],
  ], "Adverb diletakkan sebelum kata kerja utama, tetapi setelah am, is, dan are."),
  match("Match each adverb to an example sentence", [
    ["always", "I always eat breakfast"], ["never", "She never drinks coffee"],
    ["often", "We often play football"], ["sometimes", "He sometimes walks to school"],
  ], "Semua adverb ini diletakkan sebelum kata kerja utama."),
  fw(P.write, "Write one sentence about your weekend using an adverb of frequency.",
    ["present simple", "adverb of frequency"], "I usually sleep late on Sunday.",
    "Gunakan present simple dan letakkan adverb sebelum kata kerja utama."),
  fw(P.write, "Write one sentence about something you never do.", ["present simple", "adverb of frequency"],
    "I never drink coffee at night.", "Letakkan never sebelum kata kerja utama."),
];

export const adverbDegree: PoolItem[] = [
  mc(P.chooseWord, "This coffee is ___ hot.", ["very", "much", "many", "well"], "very",
    "Very diletakkan sebelum kata sifat untuk menguatkannya."),
  mc("Choose the correct position", "She is not ___ to drive.", ["old enough", "enough old", "very enough", "enough older"], "old enough",
    "Enough diletakkan setelah kata sifat, berbeda dari very."),
  mc(P.chooseWord, "The box is ___ heavy. I cannot lift it.", ["too", "enough", "quite a", "very much"], "too",
    "Too berarti terlalu, menandakan sesuatu yang berlebihan."),
  mc(P.chooseWord, "The film was ___ good.", ["really", "very much", "too much", "many"], "really",
    "Really diletakkan sebelum kata sifat untuk menguatkannya."),
  mc(P.chooseWord, "This bag is not big ___ for my books.", ["enough", "very", "too", "quite"], "enough",
    "Enough diletakkan setelah kata sifat: big enough."),
  mc(P.which, "Pick the correct sentence.",
    ["The test was quite easy.", "The test was easy quite.", "The test was quite easily."], "The test was quite easy.",
    "Quite diletakkan sebelum kata sifat, dan setelah 'was' kita memakai kata sifat easy."),
  mc(P.which, "Pick the correct sentence.",
    ["He walks very slowly.", "He walks slowly very.", "He very walks slowly."], "He walks very slowly.",
    "Adverb of degree diletakkan sebelum adverb yang dikuatkan."),
  ...conjugations("Complete the sentence", [
    ["This bag is not big ___ for my books.", "enough", "Enough diletakkan setelah kata sifat."],
    ["The soup is ___ salty. I cannot eat it.", "too", "Too berarti berlebihan sampai menjadi masalah."],
    ["Jakarta is ___ busy in the morning.", "very", "Very menguatkan kata sifat busy."],
  ]),
  wo(P.order, "The film was really good", "Adverb of degree diletakkan sebelum kata sifat."),
  wo(P.order, "He walks very slowly", "Adverb of degree bisa menguatkan adverb lain."),
  wo(P.order, "This tea is too hot", "Too diletakkan sebelum kata sifat."),
  wo(P.order, "She is quite tired today", "Quite diletakkan sebelum kata sifat."),
  match("Match each adverb to its meaning", [
    ["extremely", "very, very strong"], ["quite", "a little strong"],
    ["too", "more than we want"], ["enough", "as much as we need"],
  ], "Extremely paling kuat, quite lebih lemah, too berlebihan, enough cukup."),
  match("Match each phrase to the correct order", [
    ["old + enough", "old enough"], ["very + tall", "very tall"], ["too + hot", "too hot"], ["quite + easy", "quite easy"],
  ], "Enough diletakkan setelah kata sifat, sedangkan very, too, dan quite sebelum kata sifat."),
  fw(P.write, "Write one sentence about your city using an adverb of degree.", ["adverb of degree"],
    "Jakarta is very busy in the morning.", "Gunakan very, quite, really, atau too sebelum kata sifat."),
  fw(P.write, "Write one sentence using 'enough'.", ["adverb of degree"],
    "This room is big enough for us.", "Enough diletakkan setelah kata sifat."),
];

export const doDontDoesnt: PoolItem[] = [
  mc(P.chooseWord, "She ___ like durian.", ["don't", "doesn't", "not", "isn't"], "doesn't",
    "'She' memakai doesn't. Kata kerja setelahnya tetap bentuk dasar."),
  mc(P.chooseWord, "We ___ watch TV.", ["don't", "doesn't", "aren't", "not"], "don't",
    "'We' memakai don't + kata kerja dasar."),
  mc(P.chooseWord, "The shop ___ open on Sunday.", ["don't", "doesn't", "not", "isn't"], "doesn't",
    "'The shop' berarti it, jadi doesn't + kata kerja dasar."),
  mc(P.chooseWord, "They ___ live in Jakarta.", ["don't", "doesn't", "aren't", "not"], "don't",
    "'They' memakai don't."),
  mc(P.chooseWord, "My father ___ drink coffee.", ["doesn't", "don't", "isn't", "not"], "doesn't",
    "'My father' berarti he, jadi doesn't."),
  mc(P.which, "Pick the correct negative sentence.",
    ["She doesn't like durian.", "She doesn't likes durian.", "She don't like durian."], "She doesn't like durian.",
    "'She' memakai doesn't, dan setelahnya kata kerja kembali ke bentuk dasar."),
  mc(P.which, "Pick the correct negative sentence.",
    ["He doesn't go to school on Sunday.", "He doesn't goes to school on Sunday.", "He don't goes to school on Sunday."],
    "He doesn't go to school on Sunday.", "Setelah doesn't, kata kerja kembali ke bentuk dasar: go."),
  mc(P.which, "Pick the correct sentence.",
    ["We don't eat meat.", "We doesn't eat meat.", "We don't eats meat."], "We don't eat meat.",
    "'We' memakai don't, dan kata kerjanya tetap bentuk dasar."),
  ...conjugations("Complete the sentence using the words in brackets", [
    ["My friend ___ (not / like) K-pop.", "doesn't like", "'My friend' berarti he atau she, jadi doesn't + kata kerja dasar."],
    ["I ___ (not / eat) meat.", "don't eat", "'I' memakai don't + kata kerja dasar."],
    ["She ___ (not / watch) TV at night.", "doesn't watch", "'She' memakai doesn't + watch."],
    ["They ___ (not / play) football.", "don't play", "'They' memakai don't + play."],
    ["He ___ (not / study) on Sunday.", "doesn't study", "Setelah doesn't, study tetap bentuk dasar."],
  ]),
  flip(P.rewrite, "He writes poems.", "negative", ["He doesn't write poems.", "He does not write poems."],
    "He + doesn't + kata kerja dasar. Writes kehilangan -s."),
  flip(P.rewrite, "They watch TV at night.", "negative", ["They don't watch TV at night.", "They do not watch TV at night."],
    "'They' memakai don't + kata kerja dasar."),
  flip(P.rewrite, "She likes coffee.", "negative", ["She doesn't like coffee.", "She does not like coffee."],
    "Setelah doesn't, likes kembali menjadi like."),
  flip(P.rewrite, "I eat spicy food.", "negative", ["I don't eat spicy food.", "I do not eat spicy food."],
    "'I' memakai don't + kata kerja dasar."),
  match("Match each subject to don't or doesn't", [
    ["I", "don't"], ["He", "doesn't"], ["They", "don't"], ["My sister", "doesn't"],
  ], "I, you, we, dan they memakai don't. He, she, it, dan orang tunggal memakai doesn't."),
  match("Match each subject to don't or doesn't", [
    ["We", "don't"], ["She", "doesn't"], ["The shop", "doesn't"], ["You", "don't"],
  ], "Orang atau benda tunggal memakai doesn't."),
];
