// Exercise pools for category 1, present tenses.
import { P, conjugations, flip, fw, match, mc, wo, type PoolItem } from "./builders";

export const presentContinuous: PoolItem[] = [
  mc(P.choose, "She ___ a book right now.", ["is reading", "are reading", "am reading", "is read"], "is reading",
    "'She' memakai is, lalu kata kerja + -ing: is reading."),
  mc(P.choose, "They ___ football in the park.", ["is playing", "are playing", "am playing", "are play"], "are playing",
    "'They' jamak, jadi are + kata kerja -ing."),
  mc(P.choose, "I ___ to music at the moment.", ["am listening", "is listening", "are listening", "listening"], "am listening",
    "Dengan 'I' selalu pakai am + kata kerja -ing."),
  mc(P.choose, "The baby ___ now.", ["is sleeping", "are sleeping", "am sleeping", "is sleep"], "is sleeping",
    "'The baby' berarti it, jadi is + sleeping."),
  mc(P.choose, "We ___ for the bus.", ["are waiting", "is waiting", "am waiting", "are wait"], "are waiting",
    "'We' memakai are + kata kerja -ing."),
  mc(P.choose, "My parents ___ dinner in the kitchen.", ["are cooking", "is cooking", "am cooking", "are cook"], "are cooking",
    "'My parents' jamak, jadi are + cooking."),
  mc(P.which, "Pick the correct present continuous sentence.",
    ["She is sitting outside.", "She sitting outside.", "She is sit outside."], "She is sitting outside.",
    "Butuh dua bagian: is + kata kerja -ing. Sit menggandakan t menjadi sitting."),
  mc(P.which, "Pick the correct sentence.",
    ["He is running to school.", "He running to school.", "He is run to school."], "He is running to school.",
    "Rumusnya is + kata kerja -ing. Run menggandakan n menjadi running."),
  mc(P.choose, "Look! It ___ outside.", ["is raining", "rains", "are raining", "is rain"], "is raining",
    "'Look!' menandakan kejadian sekarang, jadi pakai present continuous: is raining."),
  ...conjugations(P.complete, [
    ["I ___ (cook) nasi goreng now.", "am cooking", "Dengan 'I' selalu pakai am: am cooking."],
    ["My father ___ (drive) to work.", "is driving", "'My father' berarti he. Kata kerja berakhiran -e kehilangan e sebelum -ing: driving."],
    ["The students ___ (write) an exam.", "are writing", "'The students' jamak, jadi are + writing."],
    ["She ___ (make) a cake.", "is making", "Make kehilangan e sebelum -ing: making."],
    ["We ___ (watch) a movie.", "are watching", "'We' memakai are + watching."],
    ["He ___ (sit) on the sofa.", "is sitting", "Sit menggandakan huruf t sebelum -ing: sitting."],
    ["They ___ (swim) in the pool.", "are swimming", "Swim menggandakan huruf m sebelum -ing: swimming."],
  ]),
  wo(P.order, "We are watching TV now", "Subjek + are + kata kerja -ing + objek + waktu."),
  wo(P.order, "She is doing her homework", "Subjek + is + kata kerja -ing + objek."),
  wo(P.order, "The children are playing outside", "Subjek jamak + are + kata kerja -ing + tempat."),
  wo(P.order, "I am waiting for my friend", "Dengan 'I' pakai am + kata kerja -ing."),
  match("Match each subject to its form of to be", [
    ["I", "am working"], ["He", "is working"], ["They", "are working"], ["It", "is working"],
  ], "I memakai am. He, she, dan it memakai is. You, we, dan they memakai are."),
  match("Match each verb to its -ing form", [
    ["drive", "driving"], ["sit", "sitting"], ["play", "playing"], ["run", "running"],
  ], "Kata kerja berakhiran -e kehilangan e (driving). Vokal + konsonan tunggal menggandakan huruf akhir (sitting, running)."),
  flip(P.rewrite, "He writes a letter.", "present_continuous", ["He is writing a letter."],
    "Present simple jadi present continuous: is + writing."),
  flip(P.rewrite, "They eat lunch.", "present_continuous", ["They are eating lunch."],
    "'They' memakai are + eating."),
  flip(P.rewrite, "She reads a book.", "present_continuous", ["She is reading a book."],
    "'She' memakai is + reading."),
  fw(P.write, "Write one sentence about what you are doing right now.", ["present continuous"],
    "I am studying English right now.", "Gunakan am/is/are + kata kerja -ing."),
  fw(P.write, "Write one sentence about what someone in your family is doing now.", ["present continuous"],
    "My mother is cooking in the kitchen.", "Gunakan is/are + kata kerja -ing untuk orang lain."),
];

export const presentSimple: PoolItem[] = [
  mc(P.choose, "The sun ___ in the east.", ["rise", "rises", "rising", "rised"], "rises",
    "'The sun' sama seperti 'it', jadi kata kerjanya mendapat -s: rises."),
  mc(P.choose, "I ___ up at 6 every day.", ["wake", "wakes", "waking", "woke"], "wake",
    "Dengan 'I', kata kerja tetap bentuk dasar: wake."),
  mc(P.choose, "She ___ English every day.", ["study", "studies", "studys", "studying"], "studies",
    "'Study' berakhiran konsonan + y, jadi dengan 'she' menjadi studies."),
  mc(P.choose, "My brother ___ in Bandung.", ["live", "lives", "living", "is live"], "lives",
    "'My brother' berarti he, jadi kata kerjanya mendapat -s: lives."),
  mc(P.choose, "They ___ Indonesian food.", ["love", "loves", "loveing", "loved"], "love",
    "'They' jamak, jadi kata kerja tetap bentuk dasar: love."),
  mc(P.choose, "My mother ___ to the market on Sunday.", ["go", "gos", "goes", "going"], "goes",
    "'Go' berakhiran -o, jadi mendapat -es: goes."),
  mc(P.choose, "Water ___ at 100°C.", ["boil", "boils", "boiling", "boiled"], "boils",
    "Kebenaran umum dengan 'water' (= it) mendapat -s: boils."),
  mc(P.which, "Pick the sentence with the correct verb form.",
    ["She studies every day.", "She study every day.", "She studys every day."], "She studies every day.",
    "'She' butuh bentuk -s, dan konsonan + y berubah menjadi -ies."),
  mc(P.which, "Pick the sentence that describes a habit.",
    ["I drink coffee every morning.", "The moon goes around the Earth.", "Ice is cold."], "I drink coffee every morning.",
    "'Every morning' menunjukkan kebiasaan berulang, jadi itu rutinitas."),
  ...conjugations(P.complete, [
    ["He ___ (watch) TV at night.", "watches", "Kata kerja berakhiran -ch mendapat -es: watches."],
    ["Water ___ (freeze) at 0°C.", "freezes", "Kebenaran umum dengan 'water' mendapat -s: freezes."],
    ["She ___ (carry) her bag.", "carries", "Konsonan + y: ubah y menjadi i lalu tambah -es: carries."],
    ["He ___ (fix) computers.", "fixes", "Kata kerja berakhiran -x mendapat -es: fixes."],
    ["It ___ (rain) a lot in Jakarta.", "rains", "Kebanyakan kata kerja cukup ditambah -s dengan 'it'."],
    ["The baby ___ (play) with the ball.", "plays", "Vokal + y cukup ditambah -s: plays, bukan plaies."],
    ["We ___ (have) class on Monday.", "have", "Dengan 'we' kata kerja tetap bentuk dasar: have."],
    ["My sister ___ (teach) English.", "teaches", "Kata kerja berakhiran -ch mendapat -es: teaches."],
  ]),
  wo(P.order, "She goes to campus every day", "Subjek + kata kerja + tempat + waktu."),
  wo(P.order, "We eat lunch together", "Subjek jamak + kata kerja dasar + objek."),
  wo(P.order, "My father reads the newspaper", "Subjek tunggal + kata kerja -s + objek."),
  match("Match each verb to its he/she/it form", [
    ["love", "loves"], ["study", "studies"], ["watch", "watches"], ["go", "goes"], ["look", "looks"],
  ], "love dan look cukup ditambah -s. watch dan go mendapat -es. study menjadi studies."),
  match("Match each sentence to its meaning", [
    ["Water boils at 100°C", "General truth"], ["She goes to campus every day", "Routine"],
    ["Cats sleep a lot", "General truth"], ["We eat lunch together", "Routine"],
  ], "Kebenaran umum selalu benar. Rutinitas adalah hal yang dilakukan secara teratur."),
  fw(P.write, "Write one sentence about something you do every day.", ["present simple"],
    "I brush my teeth every morning.", "Gunakan present simple untuk rutinitas: I + kata kerja dasar."),
  fw(P.write, "Write one sentence about a general truth.", ["present simple"],
    "The sun rises in the east.", "Kebenaran umum memakai present simple, dan he/she/it mendapat -s."),
];

export const presentPerfect: PoolItem[] = [
  mc(P.choose, "She ___ her homework.", ["has finished", "have finished", "has finish", "is finished"], "has finished",
    "He, she, dan it memakai has, lalu past participle: finished."),
  mc(P.choose, "We ___ that movie already.", ["have seen", "has seen", "have saw", "have see"], "have seen",
    "'We' memakai have. Bentuk ketiga dari see adalah seen, bukan saw."),
  mc(P.choose, "He ___ to Bali twice.", ["has been", "have been", "has been went", "has go"], "has been",
    "'He' memakai has + past participle. Bentuk ketiga dari be adalah been."),
  mc(P.choose, "They ___ their lunch.", ["have eaten", "has eaten", "have ate", "have eat"], "have eaten",
    "'They' memakai have. Bentuk ketiga dari eat adalah eaten."),
  mc(P.choose, "I ___ this book before.", ["have read", "has read", "have readed", "am read"], "have read",
    "Bentuk ketiga dari read tetap read, jadi have read."),
  mc(P.which, "Pick the correct present perfect sentence.",
    ["They have gone to Bali.", "They have went to Bali.", "They has gone to Bali."], "They have gone to Bali.",
    "'They' memakai have, dan bentuk ketiga dari go adalah gone."),
  mc(P.which, "Pick the correct sentence.",
    ["She has taken the bus.", "She has took the bus.", "She have taken the bus."], "She has taken the bus.",
    "'She' memakai has, dan bentuk ketiga dari take adalah taken."),
  ...conjugations(P.complete, [
    ["I ___ (eat) nasi goreng before.", "have eaten", "Have + past participle. Bentuk ketiga dari eat adalah eaten."],
    ["He ___ (write) three letters today.", "has written", "'He' memakai has, bentuk ketiga dari write adalah written."],
    ["We ___ (do) our homework.", "have done", "Bentuk ketiga dari do adalah done."],
    ["She ___ (see) that film.", "has seen", "'She' memakai has, bentuk ketiga dari see adalah seen."],
    ["They ___ (make) a cake.", "have made", "Bentuk ketiga dari make adalah made."],
    ["My friend ___ (buy) a new bike.", "has bought", "Bentuk ketiga dari buy adalah bought."],
  ]),
  wo(P.order, "I have never eaten durian", "Subjek + have + never + past participle."),
  wo(P.order, "She has already finished her work", "Kata already diletakkan di antara has dan past participle."),
  wo(P.order, "We have known each other for years", "Subjek + have + past participle + keterangan."),
  match("Match each verb to its past participle", [
    ["go", "gone"], ["eat", "eaten"], ["see", "seen"], ["do", "done"], ["write", "written"],
  ], "Past participle adalah bentuk ketiga: gone, eaten, seen, done, written."),
  match("Match each verb to its past participle", [
    ["take", "taken"], ["give", "given"], ["know", "known"], ["speak", "spoken"],
  ], "Bentuk ketiga dipakai setelah have/has: taken, given, known, spoken."),
  flip(P.rewrite, "She takes the bus.", "present_perfect", ["She has taken the bus."],
    "Present perfect: has + past participle. Bentuk ketiga dari take adalah taken."),
  flip(P.rewrite, "They write letters.", "present_perfect", ["They have written letters."],
    "'They' memakai have + written."),
  flip(P.rewrite, "He does his homework.", "present_perfect", ["He has done his homework."],
    "'He' memakai has, dan bentuk ketiga dari do adalah done."),
  fw(P.write, "Write one sentence about something you have done today.", ["present perfect"],
    "I have finished my homework today.", "Gunakan have/has + past participle."),
  fw(P.write, "Write one sentence about a place you have visited.", ["present perfect"],
    "I have visited Bali twice.", "Gunakan have + past participle untuk pengalaman."),
];

export const presentPerfectContinuous: PoolItem[] = [
  mc(P.choose, "I ___ English for two years.", ["have been studying", "has been studying", "have been study", "am studying"], "have been studying",
    "Rumusnya have been + kata kerja -ing. 'I' memakai have."),
  mc(P.choose, "She ___ since this morning.", ["has been working", "have been working", "has been work", "is been working"], "has been working",
    "'She' memakai has, lalu been + working."),
  mc(P.choose, "They ___ for an hour.", ["have been waiting", "has been waiting", "have being waiting", "are been waiting"], "have been waiting",
    "Bentuknya been, bukan being. 'They' memakai have."),
  mc(P.choose, "He ___ football all afternoon.", ["has been playing", "have been playing", "has been play", "is been playing"], "has been playing",
    "'He' memakai has been + playing."),
  mc("Choose for or since", "They have been waiting ___ three hours.", ["for", "since", "in", "at"], "for",
    "For dipakai untuk lama waktu. Since dipakai untuk titik mulai."),
  mc("Choose for or since", "She has been teaching here ___ 2020.", ["since", "for", "at", "in"], "since",
    "Since dipakai untuk titik mulai seperti tahun. For dipakai untuk lama waktu."),
  mc(P.which, "Pick the correct sentence.",
    ["They have been playing football.", "They have being playing football.", "They has been playing football."],
    "They have been playing football.", "Rumusnya have been, bukan have being, dan 'they' memakai have."),
  ...conjugations(P.complete, [
    ["He ___ (read) that book all day.", "has been reading", "'He' memakai has been + kata kerja -ing."],
    ["We ___ (wait) since 9 o'clock.", "have been waiting", "'We' memakai have been + waiting."],
    ["I ___ (work) here for a year.", "have been working", "Have been + working."],
    ["She ___ (cook) since noon.", "has been cooking", "'She' memakai has been + cooking."],
    ["They ___ (run) for an hour.", "have been running", "Run menggandakan huruf n sebelum -ing: running."],
  ]),
  wo(P.order, "She has been cooking for two hours", "Subjek + has been + kata kerja -ing + for + lama waktu."),
  wo(P.order, "We have been living here since 2019", "Since menandakan titik mulai."),
  wo(P.order, "I have been waiting for you", "Subjek + have been + kata kerja -ing."),
  match("Match each phrase to for or since", [
    ["two hours", "for"], ["Monday", "since"], ["a long time", "for"], ["2020", "since"],
  ], "For untuk lama waktu. Since untuk titik mulai."),
  match("Match each tense to its formula", [
    ["Present perfect", "have/has + past participle"], ["Present perfect continuous", "have/has been + verb-ing"],
    ["Present continuous", "am/is/are + verb-ing"], ["Present simple", "base verb (+ -s)"],
  ], "Present perfect continuous menggabungkan have/has been dengan kata kerja -ing."),
  fw(P.write, "Write one sentence about something you have been doing for a long time.", ["present perfect continuous"],
    "I have been learning English for three years.", "Gunakan have/has been + kata kerja -ing."),
  fw(P.write, "Write one sentence using 'since' about something you are still doing.", ["present perfect continuous"],
    "I have been studying here since 2022.", "Gunakan have been + kata kerja -ing dengan since."),
];
