// Exercise pools for category 3, future tenses.
import { P, conjugations, flip, fw, match, mc, wo, type PoolItem } from "./builders";

export const simpleFuture: PoolItem[] = [
  mc(P.chooseWord, "Tomorrow she ___ call you.", ["will", "wills", "is", "was"], "will",
    "Future: will + kata kerja dasar. Will tidak pernah berubah."),
  mc(P.chooseWord, "I ___ forget your birthday, I promise!", ["won't", "don't", "doesn't", "willn't"], "won't",
    "Negatif future: won't = will not. Bentuk willn't tidak ada."),
  mc(P.choose, "They ___ the exam next week.", ["will take", "will takes", "will taking", "wills take"], "will take",
    "Setelah will, kata kerja selalu bentuk dasar."),
  mc(P.choose, "He ___ us tomorrow.", ["will help", "will helps", "helps", "will helping"], "will help",
    "Will + kata kerja dasar, tanpa -s."),
  mc(P.chooseWord, "We ___ be late if we hurry.", ["won't", "aren't", "don't", "not"], "won't",
    "Negatif future memakai won't + kata kerja dasar."),
  mc(P.which, "Pick the correct future sentence.",
    ["She will visit Bali next year.", "She will visits Bali next year.", "She wills visit Bali next year."],
    "She will visit Bali next year.", "Setelah will, kata kerja adalah bentuk dasar, dan will tidak mendapat -s."),
  mc(P.which, "Pick the correct sentence.",
    ["They will arrive at seven.", "They will arrives at seven.", "They will arriving at seven."],
    "They will arrive at seven.", "Will + kata kerja dasar."),
  ...conjugations(P.complete, [
    ["He ___ (not / be) late.", "won't be", "Negatif future: won't + kata kerja dasar."],
    ["They ___ (arrive) at seven.", "will arrive", "Will + kata kerja dasar."],
    ["I ___ (call) you tonight.", "will call", "Will + call untuk semua subjek."],
    ["She ___ (not / come) tomorrow.", "won't come", "Won't + kata kerja dasar."],
    ["We ___ (help) you.", "will help", "Will + kata kerja dasar."],
    ["My father ___ (drive) us home.", "will drive", "Will tidak berubah walau subjeknya tunggal."],
  ]),
  wo(P.order, "We will play football tomorrow", "Subjek + will + kata kerja dasar + objek + waktu."),
  wo(P.order, "She will visit her grandmother", "Subjek + will + kata kerja dasar + objek."),
  wo(P.order, "They will not be late", "Negatif future: will not + kata kerja dasar."),
  match("Match each sentence to its future form", [
    ["I go", "I will go"], ["She eats", "She will eat"], ["They write", "They will write"], ["He has", "He will have"],
  ], "Dengan will, kata kerja kembali ke bentuk dasar."),
  match("Match each subject to its future form of be", [
    ["I", "will be"], ["She", "will be"], ["They", "will be"], ["We", "will be"],
  ], "Will be sama untuk semua subjek: will tidak pernah berubah."),
  flip(P.rewrite, "They study English.", "future", ["They will study English.", "They'll study English."],
    "Future: will + kata kerja dasar."),
  flip(P.rewrite, "I eat nasi goreng.", "future", ["I will eat nasi goreng.", "I'll eat nasi goreng."],
    "Will + eat."),
  flip(P.rewrite, "She writes a letter.", "future", ["She will write a letter.", "She'll write a letter."],
    "Setelah will, kata kerja kembali ke bentuk dasar: write."),
  fw(P.write, "Write one sentence about tomorrow.", ["future with will"],
    "Tomorrow I will visit my grandmother.", "Gunakan will + kata kerja dasar."),
  fw(P.write, "Write one sentence about something you will not do next week.", ["future with will"],
    "I will not watch television next week.", "Gunakan won't atau will not + kata kerja dasar."),
];

export const futureContinuous: PoolItem[] = [
  mc(P.choose, "At 8 tonight I ___ dinner.", ["will be cooking", "will cooking", "will be cook", "am cooking"], "will be cooking",
    "Rumusnya will be + kata kerja -ing."),
  mc(P.choose, "She ___ at the office tomorrow morning.", ["will be working", "will works", "will be work", "is be working"], "will be working",
    "Will be + working. Will tidak pernah mendapat -s."),
  mc(P.choose, "This time tomorrow we ___ to Bali.", ["will be flying", "will fly be", "will be fly", "are flying"], "will be flying",
    "Will be + kata kerja -ing untuk kegiatan yang sedang berlangsung nanti."),
  mc(P.choose, "They ___ when you arrive.", ["will be sleeping", "will sleeping", "will be sleep", "will slept"], "will be sleeping",
    "Will be + sleeping."),
  mc(P.which, "Pick the correct future continuous sentence.",
    ["He will be studying tonight.", "He will studying tonight.", "He will be study tonight."],
    "He will be studying tonight.", "Rumusnya lengkap: will + be + kata kerja -ing."),
  mc(P.which, "Pick the correct sentence.",
    ["I will be waiting for you.", "I will waiting for you.", "I will be wait for you."],
    "I will be waiting for you.", "Ketiga bagian harus ada: will, be, dan kata kerja -ing."),
  ...conjugations(P.complete, [
    ["They ___ (play) football at 4 tomorrow.", "will be playing", "Will be + kata kerja -ing."],
    ["We ___ (wait) for you at the station.", "will be waiting", "Will be + waiting."],
    ["She ___ (study) at this time tomorrow.", "will be studying", "Will be + studying."],
    ["I ___ (work) all morning.", "will be working", "Will be + working."],
    ["He ___ (drive) home at six.", "will be driving", "Drive kehilangan e sebelum -ing: driving."],
  ]),
  wo(P.order, "I will be sleeping at midnight", "Subjek + will be + kata kerja -ing + keterangan waktu."),
  wo(P.order, "They will be studying tomorrow morning", "Will be + kata kerja -ing."),
  wo(P.order, "She will be cooking dinner then", "Will be + cooking."),
  match("Match each tense to its formula", [
    ["Simple future", "will + base verb"], ["Future continuous", "will be + verb-ing"],
    ["Present continuous", "am/is/are + verb-ing"], ["Past continuous", "was/were + verb-ing"],
  ], "Future continuous menambahkan be di antara will dan kata kerja -ing."),
  match("Match each verb to its -ing form", [
    ["drive", "driving"], ["run", "running"], ["study", "studying"], ["sit", "sitting"],
  ], "Kata kerja berakhiran -e kehilangan e. Vokal + konsonan tunggal menggandakan huruf akhir."),
  flip(P.rewrite, "She is reading a book.", "future_continuous", ["She will be reading a book."],
    "Present continuous jadi future continuous: is berubah menjadi will be."),
  flip(P.rewrite, "They are playing football.", "future_continuous", ["They will be playing football."],
    "Are berubah menjadi will be."),
  fw(P.write, "Write one sentence about what you will be doing tonight.", ["future continuous"],
    "I will be watching a movie tonight.", "Gunakan will be + kata kerja -ing."),
  fw(P.write, "Write one sentence about what you will be doing this time tomorrow.", ["future continuous"],
    "This time tomorrow I will be studying English.", "Gunakan will be + kata kerja -ing."),
];

export const futurePerfect: PoolItem[] = [
  mc(P.choose, "By Friday I ___ the book.", ["will have finished", "will finished", "will have finish", "have finished"], "will have finished",
    "Rumusnya will have + past participle."),
  mc(P.choose, "She ___ the letter by tomorrow.", ["will have written", "will have write", "will has written", "will wrote"], "will have written",
    "Will have + past participle. Will have tidak pernah menjadi will has."),
  mc(P.choose, "By next month they ___ the house.", ["will have sold", "will have sell", "will has sold", "will selling"], "will have sold",
    "Will have + past participle."),
  mc(P.choose, "He ___ his work by six.", ["will have done", "will have did", "will has done", "will doing"], "will have done",
    "Bentuk ketiga dari do adalah done."),
  mc(P.which, "Pick the correct future perfect sentence.",
    ["They will have gone by six.", "They will have went by six.", "They will has gone by six."],
    "They will have gone by six.", "Will have + past participle. Bentuk ketiga dari go adalah gone."),
  mc(P.which, "Pick the correct sentence.",
    ["I will have eaten by then.", "I will have ate by then.", "I will has eaten by then."],
    "I will have eaten by then.", "Bentuk ketiga dari eat adalah eaten, dan selalu will have."),
  ...conjugations(P.complete, [
    ["They ___ (eat) before we arrive.", "will have eaten", "Will have + past participle."],
    ["By next year he ___ (learn) English.", "will have learned", "Will have + learned."],
    ["She ___ (finish) her homework by eight.", "will have finished", "Will have + finished."],
    ["We ___ (see) the film by Sunday.", "will have seen", "Bentuk ketiga dari see adalah seen."],
    ["I ___ (write) the report by Monday.", "will have written", "Bentuk ketiga dari write adalah written."],
  ]),
  wo(P.order, "We will have left by then", "Subjek + will have + past participle + keterangan waktu."),
  wo(P.order, "She will have finished her work", "Will have + past participle."),
  wo(P.order, "They will have arrived by noon", "Will have + arrived."),
  match("Match each verb to its past participle", [
    ["make", "made"], ["come", "come"], ["buy", "bought"], ["win", "won"],
  ], "Past participle dipakai setelah will have: made, come, bought, won."),
  match("Match each tense to its formula", [
    ["Simple future", "will + base verb"], ["Future perfect", "will have + past participle"],
    ["Future continuous", "will be + verb-ing"], ["Present perfect", "have/has + past participle"],
  ], "Future perfect memakai will have dengan bentuk ketiga."),
  flip(P.rewrite, "He finishes his work.", "future_perfect", ["He will have finished his work."],
    "Future perfect: will have + past participle."),
  flip(P.rewrite, "They eat dinner.", "future_perfect", ["They will have eaten dinner."],
    "Bentuk ketiga dari eat adalah eaten."),
  fw(P.write, "Write one sentence about something you will have finished by next week.", ["future perfect"],
    "I will have finished this course by next week.", "Gunakan will have + past participle."),
  fw(P.write, "Write one sentence with 'by' about the future.", ["future perfect"],
    "By Friday I will have read the whole book.", "Gunakan will have + past participle dengan by."),
];

export const futurePerfectContinuous: PoolItem[] = [
  mc(P.choose, "By June I ___ here for a year.",
    ["will have been working", "will have worked been", "will been working", "will have being working"], "will have been working",
    "Rumusnya will have been + kata kerja -ing. Bentuknya been, bukan being."),
  mc(P.choose, "She ___ for three hours by noon.",
    ["will have been studying", "will have been study", "will has been studying", "will be studied"], "will have been studying",
    "Will have been + studying. Will have tidak pernah menjadi will has."),
  mc(P.choose, "They ___ football for two hours by then.",
    ["will have been playing", "will have been play", "will been playing", "will have playing"], "will have been playing",
    "Will have been + playing."),
  mc(P.choose, "He ___ here for ten years next month.",
    ["will have been living", "will have lived been", "will has been living", "will have being living"], "will have been living",
    "Will have been + living."),
  mc(P.which, "Pick the correct sentence.",
    ["I will have been reading for an hour.", "I will have being reading for an hour.", "I will have been read for an hour."],
    "I will have been reading for an hour.", "Bentuknya been, dan kata kerja setelahnya berakhiran -ing."),
  mc("Choose for or since", "By May she will have been teaching ___ five years.", ["for", "since", "at", "by"], "for",
    "For dipakai untuk lama waktu."),
  mc("Choose for or since", "By then he will have been working here ___ 2020.", ["since", "for", "at", "in"], "since",
    "Since dipakai untuk titik mulai."),
  ...conjugations(P.complete, [
    ["They ___ (wait) for two hours by then.", "will have been waiting", "Will have been + kata kerja -ing."],
    ["He ___ (live) in Jakarta for ten years next month.", "will have been living", "Live kehilangan e sebelum -ing."],
    ["I ___ (study) for three hours by noon.", "will have been studying", "Will have been + studying."],
    ["She ___ (work) here for a year by June.", "will have been working", "Will have been + working."],
  ]),
  wo(P.order, "We will have been driving for six hours", "Subjek + will have been + kata kerja -ing + for + lama waktu."),
  wo(P.order, "They will have been waiting for an hour", "Will have been + waiting."),
  wo(P.order, "She will have been teaching for five years", "Will have been + teaching."),
  match("Match each tense to its formula", [
    ["Future perfect", "will have + past participle"], ["Future perfect continuous", "will have been + verb-ing"],
    ["Future continuous", "will be + verb-ing"], ["Simple future", "will + base verb"],
  ], "Future perfect menekankan hasil, future perfect continuous menekankan lamanya."),
  match("Match each phrase to for or since", [
    ["five years", "for"], ["2020", "since"], ["two hours", "for"], ["March", "since"],
  ], "For untuk lama waktu, since untuk titik mulai."),
  fw(P.write, "Write one sentence about how long you will have been studying English by next year.",
    ["future perfect continuous"], "By next year I will have been studying English for four years.",
    "Gunakan will have been + kata kerja -ing."),
  fw(P.write, "Write one sentence with 'by' and 'for' about the future.", ["future perfect continuous"],
    "By December I will have been working here for two years.", "Gunakan will have been + kata kerja -ing."),
];
