// Exercise pools for category 2, past tenses.
import { P, conjugations, flip, fw, match, mc, wo, type PoolItem } from "./builders";

export const pastSimple: PoolItem[] = [
  mc(P.which, "Pick the correct past sentence.", ["I went home.", "I goed home.", "I wented home."], "I went home.",
    "'Go' tak beraturan: went. Jangan menambahkan -ed pada bentuk lampau tak beraturan."),
  mc(P.choose, "Last week she ___ a letter to her grandmother.", ["writed", "wrote", "writes", "write"], "wrote",
    "Bentuk lampau dari write adalah wrote."),
  mc(P.choose, "I ___ my homework yesterday.", ["do", "did", "does", "doed"], "did",
    "'Do' tak beraturan: bentuk lampaunya did."),
  mc(P.choose, "They ___ a film last night.", ["saw", "seen", "seed", "sees"], "saw",
    "Bentuk lampau dari see adalah saw. Seen adalah bentuk ketiga."),
  mc(P.choose, "We ___ dinner at eight.", ["ate", "eated", "eaten", "eat"], "ate",
    "Bentuk lampau dari eat adalah ate."),
  mc(P.choose, "He ___ a new phone last month.", ["buyed", "bought", "buys", "buy"], "bought",
    "Bentuk lampau dari buy adalah bought."),
  mc(P.which, "Pick the correct sentence.", ["She studied all night.", "She studyed all night.", "She study all night."],
    "She studied all night.", "Konsonan + y: ubah y menjadi i lalu tambah -ed: studied."),
  ...conjugations(P.complete, [
    ["Yesterday I ___ (watch) a movie.", "watched", "'Watch' beraturan, jadi tambahkan -ed: watched."],
    ["She ___ (study) last night.", "studied", "Konsonan + y: ubah y menjadi i lalu tambah -ed."],
    ["We ___ (go) to the mall.", "went", "'Go' tak beraturan: bentuk lampaunya went."],
    ["They ___ (have) lunch at 12.", "had", "'Have' tak beraturan: bentuk lampaunya had."],
    ["He ___ (play) football on Sunday.", "played", "'Play' beraturan, cukup tambah -ed: played."],
    ["My mother ___ (cook) rendang yesterday.", "cooked", "'Cook' beraturan: cooked."],
    ["I ___ (see) my friend at the market.", "saw", "Bentuk lampau dari see adalah saw."],
    ["She ___ (write) a poem last week.", "wrote", "Bentuk lampau dari write adalah wrote."],
    ["We ___ (stop) at the station.", "stopped", "Stop menggandakan huruf p sebelum -ed: stopped."],
  ]),
  wo(P.order, "They had lunch at 12", "Subjek + kata kerja lampau + objek + waktu."),
  wo(P.order, "We went to the beach yesterday", "Keterangan waktu lampau diletakkan di akhir."),
  wo(P.order, "She watched a movie last night", "Subjek + kata kerja -ed + objek + waktu."),
  match("Match each verb to its past form", [
    ["go", "went"], ["eat", "ate"], ["have", "had"], ["see", "saw"], ["write", "wrote"],
  ], "Kata kerja tak beraturan tidak mendapat -ed: went, ate, had, saw, wrote."),
  match("Match each verb to its past form", [
    ["buy", "bought"], ["take", "took"], ["make", "made"], ["come", "came"],
  ], "Bentuk lampau tak beraturan: bought, took, made, came."),
  flip(P.rewrite, "He watches YouTube.", "past", ["He watched YouTube."],
    "'Watch' beraturan: tambahkan -ed. Tidak ada -s di bentuk lampau."),
  flip(P.rewrite, "My cat sees a bird.", "past", ["My cat saw a bird."],
    "'See' tak beraturan: bentuk lampaunya saw."),
  flip(P.rewrite, "They eat nasi goreng.", "past", ["They ate nasi goreng."],
    "Bentuk lampau dari eat adalah ate."),
  fw(P.write, "Write one sentence about something you did yesterday.", ["past simple"],
    "I visited my grandmother yesterday.", "Gunakan bentuk lampau kata kerja."),
  fw(P.write, "Write one sentence about your last holiday.", ["past simple"],
    "I went to Bali last year.", "Gunakan bentuk lampau, misalnya went."),
];

export const pastContinuous: PoolItem[] = [
  mc(P.choose, "She ___ when I called.", ["was sleeping", "were sleeping", "is sleeping", "was sleep"], "was sleeping",
    "'She' memakai was, lalu kata kerja -ing."),
  mc(P.choose, "They ___ football at 5 o'clock.", ["was playing", "were playing", "are playing", "were play"], "were playing",
    "'They' memakai were, bukan was."),
  mc(P.choose, "I ___ TV when he arrived.", ["was watching", "were watching", "am watching", "was watch"], "was watching",
    "'I' memakai was + kata kerja -ing."),
  mc(P.choose, "We ___ in the garden all morning.", ["were working", "was working", "are working", "were work"], "were working",
    "'We' memakai were + working."),
  mc(P.choose, "It ___ when we left.", ["was raining", "were raining", "is raining", "was rain"], "was raining",
    "'It' memakai was + raining."),
  mc(P.which, "Pick the correct past continuous sentence.",
    ["My parents were cooking.", "My parents was cooking.", "My parents were cook."], "My parents were cooking.",
    "'My parents' jamak, jadi were, dan kata kerjanya harus -ing."),
  mc(P.which, "Pick the correct sentence.",
    ["He was reading a book.", "He were reading a book.", "He was read a book."], "He was reading a book.",
    "'He' memakai was, dan kata kerjanya harus berakhiran -ing."),
  ...conjugations(P.complete, [
    ["I ___ (study) at 8 last night.", "was studying", "'I' memakai was + kata kerja -ing."],
    ["We ___ (eat) when he arrived.", "were eating", "'We' memakai were + eating."],
    ["She ___ (write) a letter.", "was writing", "Write kehilangan e sebelum -ing: writing."],
    ["They ___ (wait) for the bus.", "were waiting", "'They' memakai were + waiting."],
    ["He ___ (run) in the park.", "was running", "Run menggandakan huruf n sebelum -ing."],
    ["The children ___ (play) outside.", "were playing", "'The children' jamak, jadi were + playing."],
  ]),
  wo(P.order, "It was raining this morning", "Subjek + was + kata kerja -ing + keterangan waktu."),
  wo(P.order, "They were watching a movie", "Subjek jamak + were + kata kerja -ing."),
  wo(P.order, "I was cooking dinner then", "Subjek + was + kata kerja -ing + objek."),
  match("Match each subject to was or were", [
    ["I", "was"], ["She", "was"], ["They", "were"], ["You", "were"],
  ], "I, he, she, dan it memakai was. You, we, dan they memakai were."),
  match("Match each tense to its formula", [
    ["Past simple", "verb + -ed"], ["Past continuous", "was/were + verb-ing"],
    ["Present continuous", "am/is/are + verb-ing"], ["Past perfect", "had + past participle"],
  ], "Past continuous memakai was/were dengan kata kerja -ing."),
  flip(P.rewrite, "He is running.", "past_continuous", ["He was running."],
    "Present continuous jadi past continuous: is berubah menjadi was."),
  flip(P.rewrite, "They are eating.", "past_continuous", ["They were eating."],
    "'They' memakai were di bentuk lampau."),
  fw(P.write, "Write one sentence about what you were doing last night.", ["past continuous"],
    "I was watching television last night.", "Gunakan was/were + kata kerja -ing."),
  fw(P.write, "Write one sentence about what your family was doing yesterday evening.", ["past continuous"],
    "My family was watching TV yesterday evening.", "Gunakan was/were + kata kerja -ing."),
];

export const pastPerfect: PoolItem[] = [
  mc(P.choose, "She ___ before I arrived.", ["had eaten", "have eaten", "had ate", "was eaten"], "had eaten",
    "Past perfect memakai had + past participle. Bentuk ketiga dari eat adalah eaten."),
  mc(P.choose, "They ___ home when it started to rain.", ["had gone", "had went", "have gone", "had go"], "had gone",
    "Had + past participle. Bentuk ketiga dari go adalah gone, bukan went."),
  mc(P.choose, "I ___ the film before.", ["had seen", "had saw", "have saw", "had see"], "had seen",
    "Bentuk ketiga dari see adalah seen."),
  mc(P.choose, "He ___ his lunch before the meeting.", ["had finished", "have finished", "had finish", "was finished"], "had finished",
    "Had + past participle untuk semua subjek."),
  mc(P.choose, "We ___ the book before the exam.", ["had read", "had readed", "have read", "had reading"], "had read",
    "Bentuk ketiga dari read tetap read."),
  mc(P.which, "Pick the correct past perfect sentence.",
    ["She had seen that film.", "She had saw that film.", "She has had seen that film."], "She had seen that film.",
    "Had + past participle. Bentuk ketiga dari see adalah seen."),
  mc(P.which, "Pick the correct sentence.",
    ["They had taken the bus.", "They had took the bus.", "They had taking the bus."], "They had taken the bus.",
    "Bentuk ketiga dari take adalah taken."),
  ...conjugations(P.complete, [
    ["I ___ (finish) my work before dinner.", "had finished", "Had + past participle: had finished."],
    ["He ___ (write) the letter before she called.", "had written", "Bentuk ketiga dari write adalah written."],
    ["We ___ (eat) before they arrived.", "had eaten", "Bentuk ketiga dari eat adalah eaten."],
    ["She ___ (leave) before I woke up.", "had left", "Bentuk ketiga dari leave adalah left."],
    ["They ___ (do) their homework.", "had done", "Bentuk ketiga dari do adalah done."],
  ]),
  wo(P.order, "We had already left the house", "Kata already diletakkan di antara had dan past participle."),
  wo(P.order, "She had finished her work", "Subjek + had + past participle + objek."),
  wo(P.order, "They had gone home before noon", "Had + past participle untuk kejadian yang lebih dulu."),
  match("Match each verb to its past participle", [
    ["take", "taken"], ["give", "given"], ["know", "known"], ["speak", "spoken"],
  ], "Past participle dipakai setelah had: taken, given, known, spoken."),
  match("Match each verb to its past participle", [
    ["go", "gone"], ["see", "seen"], ["write", "written"], ["do", "done"],
  ], "Bentuk ketiga: gone, seen, written, done."),
  flip(P.rewrite, "He finished his homework.", "past_perfect", ["He had finished his homework."],
    "Past simple jadi past perfect: had + past participle."),
  flip(P.rewrite, "She ate breakfast.", "past_perfect", ["She had eaten breakfast."],
    "Bentuk ketiga dari eat adalah eaten."),
  fw(P.write, "Write one sentence about something you had done before you came home.", ["past perfect"],
    "I had eaten lunch before I came home.", "Gunakan had + past participle."),
  fw(P.write, "Write one sentence about something you had finished before dinner.", ["past perfect"],
    "I had finished my homework before dinner.", "Gunakan had + past participle."),
];

export const pastPerfectContinuous: PoolItem[] = [
  mc(P.choose, "They ___ for an hour when the bus came.",
    ["had been waiting", "have been waiting", "had been wait", "were been waiting"], "had been waiting",
    "Rumusnya had been + kata kerja -ing."),
  mc(P.choose, "She ___ all morning before she rested.",
    ["had been working", "has been working", "had being working", "was been working"], "had been working",
    "Had been, bukan had being. Semua subjek memakai had."),
  mc(P.choose, "I ___ for two hours before the film started.",
    ["had been studying", "have been studying", "had been study", "was been studying"], "had been studying",
    "Had been + kata kerja -ing."),
  mc(P.choose, "He ___ football before it rained.",
    ["had been playing", "had been play", "has been playing", "had playing"], "had been playing",
    "Had been + playing."),
  mc(P.which, "Pick the correct sentence.",
    ["She had been reading for an hour.", "She has been read for an hour.", "She had been read for an hour."],
    "She had been reading for an hour.", "Setelah had been, kata kerja harus berakhiran -ing."),
  mc("Choose for or since", "He had been living there ___ 2019.", ["since", "for", "at", "in"], "since",
    "Since dipakai untuk titik mulai seperti tahun."),
  mc("Choose for or since", "We had been waiting ___ two hours.", ["for", "since", "at", "by"], "for",
    "For dipakai untuk lama waktu."),
  ...conjugations(P.complete, [
    ["I ___ (study) for two hours before dinner.", "had been studying", "Had been + kata kerja -ing."],
    ["He ___ (run) before he got tired.", "had been running", "Run menggandakan huruf n sebelum -ing."],
    ["They ___ (wait) for a long time.", "had been waiting", "Had been + waiting."],
    ["She ___ (work) since morning.", "had been working", "Had been + working."],
    ["We ___ (walk) for an hour.", "had been walking", "Had been + walking."],
  ]),
  wo(P.order, "We had been cooking for two hours", "Subjek + had been + kata kerja -ing + for + lama waktu."),
  wo(P.order, "They had been playing all afternoon", "Had been + kata kerja -ing untuk menekankan lamanya."),
  wo(P.order, "She had been waiting for me", "Had been + waiting."),
  match("Match each tense to its formula", [
    ["Past continuous", "was/were + verb-ing"], ["Past perfect", "had + past participle"],
    ["Past perfect continuous", "had been + verb-ing"], ["Past simple", "verb + -ed"],
  ], "Past perfect continuous menggabungkan had been dengan kata kerja -ing."),
  match("Match each phrase to for or since", [
    ["three hours", "for"], ["Monday", "since"], ["a week", "for"], ["2019", "since"],
  ], "For untuk lama waktu, since untuk titik mulai."),
  fw(P.write, "Write one sentence about something you had been doing before you slept.", ["past perfect continuous"],
    "I had been studying for two hours before I slept.", "Gunakan had been + kata kerja -ing."),
  fw(P.write, "Write one sentence with 'for' about something you had been doing.", ["past perfect continuous"],
    "I had been waiting for an hour.", "Gunakan had been + kata kerja -ing dengan for."),
];
